### ISSUE TITLE
arrow functions aren't recommended

### ISSUE THREAD

**Issue by boneskull** [spoonscen/es6-mocha-snippets-vs-code#21]
Hi,

Great work on this extension.  However, I'm a little concerned it's  promoting a problematic style: **using arrow functions as callbacks to `describe`, `it`, and hooks is discouraged.**

Each of these callback functions runs with a context, and if you use an arrow function, you can't use the context.  For example, this works:

```js
it('should take a little while', function () {
  this.timeout(2000);
  // do something in under 2 seconds
}); 
```

...but this doesn't, because there's no `this`:

```js
it('should take a little while', () => {
  this.timeout(2000); // exception is thrown
}); 
```

Using arrow functions means if you *do* ever need the context object, then it becomes more tedious to refactor.  This is why it's discouraged.

I understand some people still prefer to write their tests this way (perhaps you included).  Maybe you'd consider a adding a warning to the `README`?  You can link [to the documentation](https://mochajs.org/#arrow-functions).

**Comment by spoonscen** [comment]
@boneskull Thank's for you interest in the project! This is definitely a discussion we have had before.
Here is the original discussion and where we landed. https://github.com/spoonscen/es6-mocha-snippets-vs-code/pull/13

I recently added a setting that you can set in your vscode settings to use `function` instead of `=>`
https://github.com/spoonscen/es6-mocha-snippets-vs-code#include-arrow-functions-normal-functions-or-both

Great suggestion about adding a link to the readme, this has already been done in #13.
https://github.com/spoonscen/es6-mocha-snippets-vs-code#arrow-functions
